id: I0BA0838C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T22:58:02+00:00'
last_modified: '2022-06-10T05:12:36.655879+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28799
  title: དྲང་ངེས་རྣམ་འབྱེད་ཀྱི་དགོངས་པའི་དོན་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    24A8:
      image_group_id: I1KG18157
      title: Volume 1 of drang nges rnam 'byed kyi dgongs pa'i don gsal bar byed pa'i
        me long /
      total_pages: 436
      order: 1
      base_file: 24A8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
